### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by Mahdilb** [lpq29743/RAM#10]
thanks for publishing the code, but i faced with an error. I run the code and add these lines in the main.py:
tf.app.flags.DEFINE_string('word2id', '', 'word to id')
tf.app.flags.DEFINE_string('max_sentence_len', '', 'max length of sentences')
tf.app.flags.DEFINE_string('max_aspect_len', '', 'max length of aspects')

after passing the first error, the new one appear. the error is :
There are 5198 words in the dataset, the max length of sentence is 79, and the max length of aspect is 23
Loading training data and testing data ...
Read 3602 sentences from data/restaurant/train.xml
Read 1120 sentences from data/restaurant/test.xml
Loading pre-trained word vectors ...
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 38, in main
    FLAGS.word2vec = load_word_embeddings(FLAGS.embedding_fname, FLAGS.embedding_dim, FLAGS.word2id)
  File "/content/RAM/utils.py", line 158, in load_word_embeddings
    word2vec[word2id[content[0]]] = np.array(list(map(float, content[1:])))
ValueError: could not convert string to float: '.'

can you help me in this ? best regards

**Comment by lpq29743** [comment]
It happens when it processes the line which contains "...", you can simply add the conditional statement `if len(content) != 301: continue` or try modifying `word2vec[word2id[content[0]]] = np.array(list(map(float, content[1:])))` to `word2vec[word2id[content[:-300]]] = np.array(list(map(float, content[-300:])))`

**Comment by Mahdilb** [comment]
Woww. Thanks a lot for your respond. I fixed it and it runs. 
I think it is necessary to mention some other points in this project which may help other in future:

first of all, I replaced `word2vec[word2id[content[0]]] = np.array(list(map(float, content[1:])))` with `word2vec[word2id[content[:-300]]] = np.array(list(map(float, content[-300:])))`, but another error appeared, it was about hashing error:
`Loading pre-trained word vectors ...
Traceback (most recent call last):
  File "main.py", line 47, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 38, in main
    FLAGS.word2vec = load_word_embeddings(FLAGS.embedding_fname, FLAGS.embedding_dim, FLAGS.word2id)
  File "/content/RAM/utils.py", line 160, in load_word_embeddings
    word2vec[word2id[content[:-300]]] = np.array(list(map(float, content[-300:])))
TypeError: unhashable type: 'list'`

then I use the other solution that you said. I mean using `if len(content) != 301: continue` in load word embeddings function in _utils.py_ . finally it works but it pointed to another issue. the error was this:

`Traceback (most recent call last):
  File "main.py", line 47, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 38, in main
    FLAGS.word2vec = load_word_embeddings(FLAGS.embedding_fname, FLAGS.embedding_dim, FLAGS.word2id)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 499, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 375, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'word2vec'`

but with your previous tip I fixed it by defining word2vec before main in `main.py`
`tf.app.flags.DEFINE_string('word2vec', '', 'word to vec')`

So i appreciate the time that you gave me and helped me in this. the paper and its performance is great. I want to delve deeper in this and find out is it possible to improve it or not?! if I get good result certainly i share it with you here. Again, Thanks a lot

**Comment by lpq29743** [comment]
I'm sorry that I haven't verified my modification. And I find the best way to correct the problem: just modify `content = line.strip().split()` to `content = line.strip().split(' ')`
