### ISSUE TITLE
关于变长序列的取平均操作

### ISSUE THREAD

**Issue by flygoinggoing** [lpq29743/RAM#3]
您的代码中使用aspect_inputs = tf.reduce_mean(aspect_inputs, 1)对target的词向量取平均，但是target是一个变长序列，这样取平均以padding后的max_len做分母，是不是应该以target的实际长度做分母？另外我用实际长度取平均时，效果却不如你这样好，我现在很困惑。。。

**Comment by lpq29743** [comment]
很抱歉这么晚才进行回复！
你的修正是合理的，按照理论上来讲效果应该是会变的更好或者是差不多。
如果效果差别很多，请检查你的实现是否有问题。如果没有问题，可以尝试调参。
由于数据集样本不是特别多，所以效果基本不可能因为这样一个操作的修改而在效果上有比较大的提升。

**Comment by flygoinggoing** [comment]
如果不是看到您的回复，我甚至都已经忘记我提过这个问题，哈哈。
非常感谢！
