### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by saja1994** [lpq29743/RAM#7]
Hello,

Please, I want to ask you about the implemented Bidirectional LSTM (Bi-LSTM), is it a deep one? because it is mentioned in the RAM paper that the proposed approach uses 2 layers of (Bi-LSTM) but I can't see that in your code! 

Thank you,

**Comment by lpq29743** [comment]
Actually, I implemented BiLSTM with single layer here. I have tried to implement a BiLSTM network with two  layers but achieve a worse result. Maybe it's because some details I implemented (i.e. hyperparameter setting) are different from the author did.

**Comment by saja1994** [comment]
Okay, thank you for your efforts.
