### ISSUE TITLE
Visualize the attention

### ISSUE THREAD

**Issue by saja1994** [lpq29743/RAM#9]
Hello

Thank you for the implementation. Please, can you help me to visualize the attention weights at each hop as mentioned figures in the original paper?

Regards,

**Comment by lpq29743** [comment]
1. As mentioned in “Yequan Wang, Minlie Huang, Xiaoyan Zhu, and Li Zhao. 2016. Attention-based lstm for aspect-level sentiment classification. In EMNLP, pages 606–615.”, HEMI (Wankun Deng, Yongbo Wang, Zexian Liu, Han Cheng, and Yu Xue. 2014. Hemi: a toolkit for illustrating heatmaps. PloS one, 9(11):e111988.) was used to visualize the attention.
2. Actually, I can't find some effective tools to visualize the attention, welcome to share your method if you find some useful tools.

**Comment by saja1994** [comment]
Thank you. Yes, I have used HEMI to visualize the attention. it's a simple and straightforward program to be used,
